name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  serverless-deploy:
    runs-on: ubuntu-18.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      S3_BUCKET: ${{secrets.S3_BUCKET}}
      apiUrl: ${{secrets.API_URL}}
      apiSearchUrl: ${{secrets.API_SEARCH_URL}}
      googleAnalyticsTag: ${{secrets.GOOGLE_ANALYTICS_TAG}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install serverless
        run: yarn add -D serverless

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://${{secrets.S3_BUCKET}}/ohys-schedule/prod/.serverless .serverless --delete

      - name: Deploy to AWS
        run: yarn deploy

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://${{secrets.S3_BUCKET}}/ohys-schedule/prod/.serverless --delete
